<?xml version="1.0" encoding="utf-8"?><Database Name="IFM_Project" Class="CyberLlamaDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\v12.0;Initial Catalog=IFM_Project;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="IFM_ProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Admin_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Conrtact_Number" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="LoginTable_Admin" Member="LoginTable" ThisKey="Admin_ID" OtherKey="User_ID" Type="LoginTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AirCooler" Member="AirCoolers">
    <Type Name="AirCooler">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Compatibility" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_RPM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Air_Flow" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Noise_Level" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Power_Connector" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Materials" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Heatsink_Dimentions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Features" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Package_Contents" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="AirCooler_CpuToAirCooler" Member="CpuToAirCoolers" ThisKey="Model" OtherKey="Cooler_Model" Type="CpuToAirCooler" />
    </Type>
  </Table>
  <Table Name="dbo.CaseToMobo" Member="CaseToMobos">
    <Type Name="CaseToMobo">
      <Column Name="Case_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mobo_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Motherboard_CaseToMobo" Member="Motherboard" ThisKey="Mobo_Model" OtherKey="Model" Type="Motherboard" IsForeignKey="true" />
      <Association Name="PCCase_CaseToMobo" Member="PCCase" ThisKey="Case_Model" OtherKey="Model" Type="PCCase" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ZIP_Code" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="LoginTable_Client" Member="LoginTable" ThisKey="User_ID" OtherKey="User_ID" Type="LoginTable" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CPU" Member="CPUs">
    <Type Name="CPU">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Architecture" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cores" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Threads" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Base_Clock" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Boost_Clock" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Total_L1_Cache" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Total_L2_Cache" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Total_L3_Cache" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CMOS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pakage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TDP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Temp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="System_Memory_Speed" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="System_Memory_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Channels" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Supported_Tech" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="CPU_CpuToAirCooler" Member="CpuToAirCoolers" ThisKey="Model" OtherKey="CPU_Model" Type="CpuToAirCooler" />
      <Association Name="CPU_CpuToLiquidCooler" Member="CpuToLiquidCoolers" ThisKey="Model" OtherKey="CPU_Model" Type="CpuToLiquidCooler" />
      <Association Name="CPU_MoboToCPU" Member="MoboToCPUs" ThisKey="Model" OtherKey="CPU_Model" Type="MoboToCPU" />
    </Type>
  </Table>
  <Table Name="dbo.CpuToAirCooler" Member="CpuToAirCoolers">
    <Type Name="CpuToAirCooler">
      <Column Name="CPU_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cooler_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AirCooler_CpuToAirCooler" Member="AirCooler" ThisKey="Cooler_Model" OtherKey="Model" Type="AirCooler" IsForeignKey="true" />
      <Association Name="CPU_CpuToAirCooler" Member="CPU" ThisKey="CPU_Model" OtherKey="Model" Type="CPU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CpuToLiquidCooler" Member="CpuToLiquidCoolers">
    <Type Name="CpuToLiquidCooler">
      <Column Name="CPU_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Liquid_Cooler_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CPU_CpuToLiquidCooler" Member="CPU" ThisKey="CPU_Model" OtherKey="Model" Type="CPU" IsForeignKey="true" />
      <Association Name="LiquidCooler_CpuToLiquidCooler" Member="LiquidCooler" ThisKey="Liquid_Cooler_Model" OtherKey="Model" Type="LiquidCooler" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fans" Member="Fans">
    <Type Name="Fan">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RPM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Air_Flow" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Noise" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Static_Pressure" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Input_Voltage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MBTF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cable_Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Package_Contents" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GPU" Member="GPUs">
    <Type Name="GPU">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Chipset" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Interface" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Clock_Speed_Base" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Clock_Speed_Boost" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Stream_Processors" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Clock" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Interface" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ports" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Digital_Resolution" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VR_Ready" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CrossFire_Support" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Recommended_Power_Supply" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Form_Factor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Slot_Width" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="GPU_GpuToMonitor" Member="GpuToMonitors" ThisKey="Model" OtherKey="GPU_Model" Type="GpuToMonitor" />
    </Type>
  </Table>
  <Table Name="dbo.GpuToMonitor" Member="GpuToMonitors">
    <Type Name="GpuToMonitor">
      <Column Name="GPU_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Monitor_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Display_Ports" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HDMI" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="VGA" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="GPU_GpuToMonitor" Member="GPU" ThisKey="GPU_Model" OtherKey="Model" Type="GPU" IsForeignKey="true" />
      <Association Name="Monitor_GpuToMonitor" Member="Monitor" ThisKey="Monitor_Model" OtherKey="Model" Type="Monitor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HDD" Member="HDDs">
    <Type Name="HDD">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Interface" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Bytes_Per_Sector" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Sustained_Transfer_Rate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rotational_Speed" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Load_Unload_Cycles" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Workload_Rate_Limit" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Idle_Power_Usage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Typical_Power_Usage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Operating_Temp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Storage_Temp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Headset" Member="Headsets">
    <Type Name="Headset">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Cable_Length" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Connector" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Compatibility" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Frequency_Response" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sound_Pressure_Level" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Microphone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MP_Frequency_Response" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MP_Pickup_Pattern" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MP_Sensitivity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Wearing_Style" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Features" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Keyboard" Member="Keyboards">
    <Type Name="Keyboard">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Switches" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Programmable_Macros" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Connector" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LED_BackLight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Multimedia_Keys" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Material" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LiquidCooler" Member="LiquidCoolers">
    <Type Name="LiquidCooler">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_RPM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_PWM_Control" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Noise" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Max_Air_Flow" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Max_Static_Pressure" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Input_Voltage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_MTBF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pump_RPM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pump_PWM_Control" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pump_Max_Pressure" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pump_Rated_Input_Power" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pump_MTBF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Radiator_Housing_Mats" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Radiator_Fin_Mats" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Screw_Threads" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Radiator_Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Coldplate_Material" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Thermal_Paste" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fittings" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Tube_Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tube_Mats" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sockets_Supported" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="RGB" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Package_Contents" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LiquidCooler_CpuToLiquidCooler" Member="CpuToLiquidCoolers" ThisKey="Model" OtherKey="Liquid_Cooler_Model" Type="CpuToLiquidCooler" />
    </Type>
  </Table>
  <Table Name="dbo.LoginTable" Member="LoginTables">
    <Type Name="LoginTable">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="User_Type" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="LoginTable_Admin" Member="Admin" ThisKey="User_ID" OtherKey="Admin_ID" Type="Admin" Cardinality="One" />
      <Association Name="LoginTable_Client" Member="Client" ThisKey="User_ID" OtherKey="User_ID" Type="Client" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Microphone" Member="Microphones">
    <Type Name="Microphone">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Pick_Up_Pattern" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Frequency_Response" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sensitivity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cable_Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MoboToCPU" Member="MoboToCPUs">
    <Type Name="MoboToCPU">
      <Column Name="Mobo_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CPU_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CPU_Chipset" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="CPU_MoboToCPU" Member="CPU" ThisKey="CPU_Model" OtherKey="Model" Type="CPU" IsForeignKey="true" />
      <Association Name="Motherboard_MoboToCPU" Member="Motherboard" ThisKey="Mobo_Model" OtherKey="Model" Type="Motherboard" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MoboToRAM" Member="MoboToRAMs">
    <Type Name="MoboToRAM">
      <Column Name="Mobo_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RAM_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Motherboard_MoboToRAM" Member="Motherboard" ThisKey="Mobo_Model" OtherKey="Model" Type="Motherboard" IsForeignKey="true" />
      <Association Name="RAM_MoboToRAM" Member="RAM" ThisKey="RAM_Model" OtherKey="Model" Type="RAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Monitor" Member="Monitors">
    <Type Name="Monitor">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ScreenSize" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ScreenRatio" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Brightness" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContrastRatio" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DynamicContrastRatio" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ViewingAngle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResponseTime" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Panel Type]" Member="Panel_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RefreshRate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Resolution" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Colours" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayPortInput" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HDMI" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VGA" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Speakers" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PowerSource" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PowerSupply" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EnergyClass" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Swivel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tilt" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Pivot]" Member="Pivot" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Regulations" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Monitor_GpuToMonitor" Member="GpuToMonitors" ThisKey="Model" OtherKey="Monitor_Model" Type="GpuToMonitor" />
    </Type>
  </Table>
  <Table Name="dbo.Motherboard" Member="Motherboards">
    <Type Name="Motherboard">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Chipset" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Type" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Memory_Size" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Max_Memory_Speed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Audio" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LAN" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Expansion_Slots" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Storage_Interface" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Multi_GPU_Tech" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="USB" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[Internal_I/O_Connectors]" Member="Internal_I_O_Connectors" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Back_Panel_Connectors" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[I/O_Controller]" Member="I_O_Controller" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BIOS" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OS_Support" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Form_Factor" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Motherboard_CaseToMobo" Member="CaseToMobos" ThisKey="Model" OtherKey="Mobo_Model" Type="CaseToMobo" />
      <Association Name="Motherboard_MoboToCPU" Member="MoboToCPUs" ThisKey="Model" OtherKey="Mobo_Model" Type="MoboToCPU" />
      <Association Name="Motherboard_MoboToRAM" Member="MoboToRAMs" ThisKey="Model" OtherKey="Mobo_Model" Type="MoboToRAM" />
    </Type>
  </Table>
  <Table Name="dbo.Mouse" Member="Mouses">
    <Type Name="Mouse">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Sensor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Resolution" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Acceleration" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Speed" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Connection_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Durability" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PTFE_Feet" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Battery" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cable_Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OS_Support" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MousePad" Member="MousePads">
    <Type Name="MousePad">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Materials" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Base" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Features" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OS" Member="OS">
    <Type Name="OS">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Bit_Version" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OS_Version" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="System_Requirements" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PCCase" Member="PCCases">
    <Type Name="PCCase">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Net_Weight" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Motherboard_Support" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="[Num_5.25&quot;_Drives]" Member="Num_5_25__Drives" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Num_3.5&quot;_Drives]" Member="Num_3_5__Drives" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Num_2.5&quot;_Drives]" Member="Num_2_5__Drives" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[I/O_Port]" Member="I_O_Port" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Expansion_Slots" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Num_Top_Fans" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Num_Bottom_Fans" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Num_Front_Fans" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Num_Back_Fans" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Top_Radiator_Support" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Front_Radiator_Support" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PSU_Support" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GPU_Max_Length" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CPU_Cooler_Height" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PCCase_CaseToMobo" Member="CaseToMobos" ThisKey="Model" OtherKey="Case_Model" Type="CaseToMobo" />
      <Association Name="PCCase_PSUtoCase" Member="PSUtoCases" ThisKey="Model" OtherKey="Case_Model" Type="PSUtoCase" />
    </Type>
  </Table>
  <Table Name="dbo.PSU" Member="PSUs">
    <Type Name="PSU">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Power" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Certification" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Modular" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Connectors" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MTBF" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Size" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Cables" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Compatability" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Package_Content" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="PSU_PSUtoCase" Member="PSUtoCases" ThisKey="Model" OtherKey="PSU_Model" Type="PSUtoCase" />
    </Type>
  </Table>
  <Table Name="dbo.PSUtoCase" Member="PSUtoCases">
    <Type Name="PSUtoCase">
      <Column Name="Case_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PSU_Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Max_Watts" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="PCCase_PSUtoCase" Member="PCCase" ThisKey="Case_Model" OtherKey="Model" Type="PCCase" IsForeignKey="true" />
      <Association Name="PSU_PSUtoCase" Member="PSU" ThisKey="PSU_Model" OtherKey="Model" Type="PSU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RAM" Member="RAMs">
    <Type Name="RAM">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Speed" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Latency" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Voltage" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SPD_Speed" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SPD_Voltage" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Channel_Config" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="RAM_MoboToRAM" Member="MoboToRAMs" ThisKey="Model" OtherKey="RAM_Model" Type="MoboToRAM" />
    </Type>
  </Table>
  <Table Name="dbo.Speaker" Member="Speakers">
    <Type Name="Speaker">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Satellite_Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Satellite_Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubWoofer_Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubWoofer_Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="controls" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[System Requirements]" Member="System_Requirements" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Features" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SSD" Member="SSDs">
    <Type Name="SSD">
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Form_Factor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Interface" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Sequential_Read" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Sequential_Write" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[4KB_Random_Read]" Member="_4KB_Random_Read" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[4KB_Random_Write]" Member="_4KB_Random_Write" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Seek_Time" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MTBF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Operating_Temp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Storage_Temp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Idle_Power_Usage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Power_Usage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warrenty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>