<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="CyberLlamaDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Admin_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Conrtact_Number" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserPosition_Admin" Member="UserPosition" ThisKey="Position" OtherKey="PositionID" Type="UserPosition" IsForeignKey="true" />
      <Association Name="LoginTable_Admin" Member="LoginTable" ThisKey="Admin_ID" OtherKey="User_ID" Type="LoginTable" IsForeignKey="true" />
      <Association Name="UserPosition1_Admin" Member="UserPosition1" ThisKey="Position" OtherKey="PositionID" Type="UserPosition1" IsForeignKey="true" />
      <Association Name="LoginTable1_Admin" Member="LoginTable1" ThisKey="Admin_ID" OtherKey="User_ID" Type="LoginTable1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserPosition" Member="UserPositions">
    <Type Name="UserPosition">
      <Column Name="PositionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="UserPosition_Admin" Member="Admins" ThisKey="PositionID" OtherKey="Position" Type="Admin" />
      <Association Name="UserPosition_Admin1" Member="Admin1s" ThisKey="PositionID" OtherKey="Position" Type="Admin1" />
    </Type>
  </Table>
  <Table Name="dbo.AirCooler" Member="AirCoolers">
    <Type Name="AirCooler">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Compatibility" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_RPM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Air_Flow" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Noise_Level" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Power_Connector" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Materials" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Features" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="AirCooler_CpuToAirCooler" Member="CpuToAirCoolers" ThisKey="ID" OtherKey="AC_ID" Type="CpuToAirCooler" />
      <Association Name="AirCooler_CpuToAirCooler1" Member="CpuToAirCooler1s" ThisKey="ID" OtherKey="AC_ID" Type="CpuToAirCooler1" />
      <Association Name="PartsStock_AirCooler" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_AirCooler" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ZIP_Code" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Client_PartInvoice" Member="PartInvoices" ThisKey="User_ID" OtherKey="User_ID" Type="PartInvoice" />
      <Association Name="Client_PcInvoice" Member="PcInvoices" ThisKey="User_ID" OtherKey="User_ID" Type="PcInvoice" />
      <Association Name="Client_PartCart" Member="PartCarts" ThisKey="User_ID" OtherKey="User_ID" Type="PartCart" />
      <Association Name="Client_PcCart" Member="PcCarts" ThisKey="User_ID" OtherKey="User_ID" Type="PcCart" />
      <Association Name="Client_PartCart1" Member="PartCart1s" ThisKey="User_ID" OtherKey="User_ID" Type="PartCart1" />
      <Association Name="Client_PartInvoice1" Member="PartInvoice1s" ThisKey="User_ID" OtherKey="User_ID" Type="PartInvoice1" />
      <Association Name="Client_PcCart1" Member="PcCart1s" ThisKey="User_ID" OtherKey="User_ID" Type="PcCart1" />
      <Association Name="Client_PcInvoice1" Member="PcInvoice1s" ThisKey="User_ID" OtherKey="User_ID" Type="PcInvoice1" />
      <Association Name="LoginTable_Client" Member="LoginTable" ThisKey="User_ID" OtherKey="User_ID" Type="LoginTable" IsForeignKey="true" />
      <Association Name="LoginTable1_Client" Member="LoginTable1" ThisKey="User_ID" OtherKey="User_ID" Type="LoginTable1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CpuToAirCooler" Member="CpuToAirCoolers">
    <Type Name="CpuToAirCooler">
      <Column Name="CPU_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AC_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AirCooler_CpuToAirCooler" Member="AirCooler" ThisKey="AC_ID" OtherKey="ID" Type="AirCooler" IsForeignKey="true" />
      <Association Name="CPU_CpuToAirCooler" Member="CPU" ThisKey="CPU_ID" OtherKey="ID" Type="CPU" IsForeignKey="true" />
      <Association Name="AirCooler1_CpuToAirCooler" Member="AirCooler1" ThisKey="AC_ID" OtherKey="ID" Type="AirCooler1" IsForeignKey="true" />
      <Association Name="CPU1_CpuToAirCooler" Member="CPU1" ThisKey="CPU_ID" OtherKey="ID" Type="CPU1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CpuToLiquidCooler" Member="CpuToLiquidCoolers">
    <Type Name="CpuToLiquidCooler">
      <Column Name="CPU_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LC_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CPU_CpuToLiquidCooler" Member="CPU" ThisKey="CPU_ID" OtherKey="ID" Type="CPU" IsForeignKey="true" />
      <Association Name="LiquidCooler_CpuToLiquidCooler" Member="LiquidCooler" ThisKey="LC_ID" OtherKey="ID" Type="LiquidCooler" IsForeignKey="true" />
      <Association Name="CPU_CpuToLiquidCooler" Member="CPU" ThisKey="CPU_ID" OtherKey="ID" Type="CPU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GpuToMonitor" Member="GpuToMonitors">
    <Type Name="GpuToMonitor">
      <Column Name="GPU_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Monitor_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Monitor_GpuToMonitor" Member="Monitor" ThisKey="Monitor_ID" OtherKey="ID" Type="Monitor" IsForeignKey="true" />
      <Association Name="GPU_GpuToMonitor" Member="GPU" ThisKey="GPU_ID" OtherKey="ID" Type="GPU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Headset" Member="Headsets">
    <Type Name="Headset">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Cable_Length" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Connector" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Compatibility" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Frequency_Response" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sound_Pressure_Level" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Microphone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MP_Frequency_Response" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MP_Pickup_Pattern" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MP_Sensitivity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Wearing_Style" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Features" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Headset_Pc" Member="Pcs" ThisKey="ID" OtherKey="Headset_ID" Type="Pc" />
      <Association Name="Headset_Pc1" Member="Pc1s" ThisKey="ID" OtherKey="Headset_ID" Type="Pc1" />
      <Association Name="PartsStock_Headset" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_Headset" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Keyboard" Member="Keyboards">
    <Type Name="Keyboard">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Switches" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Programmable_Macros" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Connector" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LED_BackLight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Multimedia_Keys" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Material" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Keyboard_Pc" Member="Pcs" ThisKey="ID" OtherKey="Keyboard_ID" Type="Pc" />
      <Association Name="Keyboard_Pc1" Member="Pc1s" ThisKey="ID" OtherKey="Keyboard_ID" Type="Pc1" />
      <Association Name="PartsStock_Keyboard" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_Keyboard" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LiquidCooler" Member="LiquidCoolers">
    <Type Name="LiquidCooler">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Height" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Radiator_Mats" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Radiator_Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Radiator_Width" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Radiator_Height" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tube_Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tube_Mats" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sockets_Supported" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RGB" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LiquidCooler_CpuToLiquidCooler" Member="CpuToLiquidCoolers" ThisKey="ID" OtherKey="LC_ID" Type="CpuToLiquidCooler" />
      <Association Name="LiquidCooler_Pc" Member="Pcs" ThisKey="ID" OtherKey="Cooler_ID" Type="Pc" />
      <Association Name="LiquidCooler_CpuToLiquidCooler1" Member="CpuToLiquidCooler1s" ThisKey="ID" OtherKey="LC_ID" Type="CpuToLiquidCooler1" />
      <Association Name="LiquidCooler_Pc1" Member="Pc1s" ThisKey="ID" OtherKey="Cooler_ID" Type="Pc1" />
      <Association Name="PartsStock_LiquidCooler" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_LiquidCooler" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoginTable" Member="LoginTables">
    <Type Name="LoginTable">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="User_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LoginTable_Admin" Member="Admin" ThisKey="User_ID" OtherKey="Admin_ID" Type="Admin" Cardinality="One" />
      <Association Name="LoginTable_Client" Member="Client" ThisKey="User_ID" OtherKey="User_ID" Type="Client" Cardinality="One" />
      <Association Name="LoginTable_Admin1" Member="Admin1" ThisKey="User_ID" OtherKey="Admin_ID" Type="Admin1" Cardinality="One" />
      <Association Name="LoginTable_Client1" Member="Client1" ThisKey="User_ID" OtherKey="User_ID" Type="Client1" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Microphone" Member="Microphones">
    <Type Name="Microphone">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Pick_Up_Pattern" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Frequency_Response" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sensitivity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cable_Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PartsStock_Microphone" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_Microphone" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MoboToRam" Member="MoboToRams">
    <Type Name="MoboToRam">
      <Column Name="Mobo_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RAM_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Motherboard_MoboToRam" Member="Motherboard" ThisKey="Mobo_ID" OtherKey="ID" Type="Motherboard" IsForeignKey="true" />
      <Association Name="RAM_MoboToRam" Member="RAM" ThisKey="RAM_ID" OtherKey="ID" Type="RAM" IsForeignKey="true" />
      <Association Name="Motherboard1_MoboToRam" Member="Motherboard1" ThisKey="Mobo_ID" OtherKey="ID" Type="Motherboard1" IsForeignKey="true" />
      <Association Name="RAM1_MoboToRam" Member="RAM1" ThisKey="RAM_ID" OtherKey="ID" Type="RAM1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Monitor" Member="Monitors">
    <Type Name="Monitor">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ScreenSize" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ScreenRatio" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Brightness" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContrastRatio" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DynamicContrastRatio" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ViewingAngle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResponseTime" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Panel Type]" Member="Panel_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RefreshRate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Resolution" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Colours" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayPortInput" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HDMI" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VGA" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Speakers" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PowerSource" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PowerSupply" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EnergyClass" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Swivel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tilt" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Pivot]" Member="Pivot" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Regulations" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Monitor_Pc" Member="Pcs" ThisKey="ID" OtherKey="Monitor_ID" Type="Pc" />
      <Association Name="Monitor_Pc1" Member="Pc1s" ThisKey="ID" OtherKey="Monitor_ID" Type="Pc1" />
      <Association Name="PartsStock_Monitor" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_Monitor" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Motherboard" Member="Motherboards">
    <Type Name="Motherboard">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Chipset" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Type" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Memory_Size" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Max_Memory_Speed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LAN" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Expansion_Slots" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Storage" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[Internal_I/O_Connectors]" Member="Internal_I_O_Connectors" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Back_Panel_Connectors" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="OS_Support" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Form_Factor" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Warranty" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Motherboard_MoboToCase" Member="MoboToCases" ThisKey="ID" OtherKey="Mobo_ID" Type="MoboToCase" />
      <Association Name="Motherboard_MoboToCpu" Member="MoboToCpus" ThisKey="ID" OtherKey="Mobo_ID" Type="MoboToCpu" />
      <Association Name="Motherboard_MoboToRam" Member="MoboToRams" ThisKey="ID" OtherKey="Mobo_ID" Type="MoboToRam" />
      <Association Name="Motherboard_Pc" Member="Pcs" ThisKey="ID" OtherKey="Mobo_ID" Type="Pc" />
      <Association Name="Motherboard_MoboToCase" Member="MoboToCases" ThisKey="ID" OtherKey="Mobo_ID" Type="MoboToCase" />
      <Association Name="Motherboard_MoboToCpu" Member="MoboToCpus" ThisKey="ID" OtherKey="Mobo_ID" Type="MoboToCpu" />
      <Association Name="PartsStock_Motherboard" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_Motherboard" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mouse" Member="Mouses">
    <Type Name="Mouse">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Sensor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Resolution" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Acceleration" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Speed" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Connection_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Durability" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PTFE_Feet" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Battery" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cable_Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OS_Support" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Mouse_Pc" Member="Pcs" ThisKey="ID" OtherKey="Mouse_ID" Type="Pc" />
      <Association Name="Mouse_Pc1" Member="Pc1s" ThisKey="ID" OtherKey="Mouse_ID" Type="Pc1" />
      <Association Name="PartsStock_Mouse" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_Mouse" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MousePad" Member="MousePads">
    <Type Name="MousePad">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Materials" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Base" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Features" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PartsStock_MousePad" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_MousePad" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OperatingSystem" Member="OperatingSystems">
    <Type Name="OperatingSystem">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Bit_Version" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OS_Version" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="System_Requirements" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PartsStock_OperatingSystem" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_OperatingSystem" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PartCart" Member="PartCarts">
    <Type Name="PartCart">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Part_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Qua" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Client_PartCart" Member="Client" ThisKey="User_ID" OtherKey="User_ID" Type="Client" IsForeignKey="true" />
      <Association Name="PartsStock_PartCart" Member="PartsStock" ThisKey="Part_ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PartsSold" Member="PartsSolds">
    <Type Name="PartsSold">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity_Sold" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PartsStock_PartsSold" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_PartsSold" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PartsStock" Member="PartsStocks">
    <Type Name="PartsStock">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PartsStock_AirCooler" Member="AirCooler" ThisKey="ID" OtherKey="ID" Type="AirCooler" Cardinality="One" />
      <Association Name="PartsStock_CPU" Member="CPU" ThisKey="ID" OtherKey="ID" Type="CPU" Cardinality="One" />
      <Association Name="PartsStock_Fan" Member="Fan" ThisKey="ID" OtherKey="ID" Type="Fan" Cardinality="One" />
      <Association Name="PartsStock_GPU" Member="GPU" ThisKey="ID" OtherKey="ID" Type="GPU" Cardinality="One" />
      <Association Name="PartsStock_HDD" Member="HDD" ThisKey="ID" OtherKey="ID" Type="HDD" Cardinality="One" />
      <Association Name="PartsStock_Headset" Member="Headset" ThisKey="ID" OtherKey="ID" Type="Headset" Cardinality="One" />
      <Association Name="PartsStock_Keyboard" Member="Keyboard" ThisKey="ID" OtherKey="ID" Type="Keyboard" Cardinality="One" />
      <Association Name="PartsStock_LiquidCooler" Member="LiquidCooler" ThisKey="ID" OtherKey="ID" Type="LiquidCooler" Cardinality="One" />
      <Association Name="PartsStock_Microphone" Member="Microphone" ThisKey="ID" OtherKey="ID" Type="Microphone" Cardinality="One" />
      <Association Name="PartsStock_Monitor" Member="Monitor" ThisKey="ID" OtherKey="ID" Type="Monitor" Cardinality="One" />
      <Association Name="PartsStock_Motherboard" Member="Motherboard" ThisKey="ID" OtherKey="ID" Type="Motherboard" Cardinality="One" />
      <Association Name="PartsStock_Mouse" Member="Mouse" ThisKey="ID" OtherKey="ID" Type="Mouse" Cardinality="One" />
      <Association Name="PartsStock_MousePad" Member="MousePad" ThisKey="ID" OtherKey="ID" Type="MousePad" Cardinality="One" />
      <Association Name="PartsStock_OperatingSystem" Member="OperatingSystem" ThisKey="ID" OtherKey="ID" Type="OperatingSystem" Cardinality="One" />
      <Association Name="PartsStock_PartCart" Member="PartCarts" ThisKey="ID" OtherKey="Part_ID" Type="PartCart" />
      <Association Name="PartsStock_PartsSold" Member="PartsSold" ThisKey="ID" OtherKey="ID" Type="PartsSold" Cardinality="One" />
      <Association Name="PartsStock_PCCase" Member="PCCase" ThisKey="ID" OtherKey="ID" Type="PCCase" Cardinality="One" />
      <Association Name="PartsStock_PSU" Member="PSU" ThisKey="ID" OtherKey="ID" Type="PSU" Cardinality="One" />
      <Association Name="PartsStock_RAM" Member="RAM" ThisKey="ID" OtherKey="ID" Type="RAM" Cardinality="One" />
      <Association Name="PartsStock_Speaker" Member="Speaker" ThisKey="ID" OtherKey="ID" Type="Speaker" Cardinality="One" />
      <Association Name="PartsStock_AirCooler" Member="AirCooler" ThisKey="ID" OtherKey="ID" Type="AirCooler" Cardinality="One" />
      <Association Name="PartsStock_PartCart" Member="PartCarts" ThisKey="ID" OtherKey="Part_ID" Type="PartCart" />
      <Association Name="PartsStock_GPU" Member="GPU" ThisKey="ID" OtherKey="ID" Type="GPU" Cardinality="One" />
      <Association Name="PartsStock_HDD" Member="HDD" ThisKey="ID" OtherKey="ID" Type="HDD" Cardinality="One" />
      <Association Name="PartsStock_SSD" Member="SSD" ThisKey="ID" OtherKey="ID" Type="SSD" Cardinality="One" />
      <Association Name="PartsStock_CPU" Member="CPU" ThisKey="ID" OtherKey="ID" Type="CPU" Cardinality="One" />
      <Association Name="PartsStock_Fan" Member="Fan" ThisKey="ID" OtherKey="ID" Type="Fan" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.PCCase" Member="PCCases">
    <Type Name="PCCase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Net_Weight" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Motherboard_Form_Factor" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Side_Window" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Num_HDD_Drives" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Num_SSD_Drives" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Front_I/O]" Member="Front_I_O" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Expansion_Slots" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Num_Top_Fans" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Num_Bottom_Fans" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Num_Front_Fans" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Num_Back_Fans" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Top_Radiator_Support" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Front_Radiator_Support" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GPU_Max_Length" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CPU_Cooler_Height" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PCCase_MoboToCase" Member="MoboToCases" ThisKey="ID" OtherKey="Case_ID" Type="MoboToCase" />
      <Association Name="PCCase_Pc" Member="Pcs" ThisKey="ID" OtherKey="Case_ID" Type="Pc" />
      <Association Name="PCCase_MoboToCase" Member="MoboToCases" ThisKey="ID" OtherKey="Case_ID" Type="MoboToCase" />
      <Association Name="PartsStock_PCCase" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_PCCase" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PcSold" Member="PcSolds">
    <Type Name="PcSold">
      <Column Name="PC_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity_Sold" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PcStock_PcSold" Member="PcStock" ThisKey="PC_ID" OtherKey="ID" Type="PcStock" IsForeignKey="true" />
      <Association Name="PcStock1_PcSold" Member="PcStock1" ThisKey="PC_ID" OtherKey="ID" Type="PcStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PSU" Member="PSUs">
    <Type Name="PSU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Power" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Certification" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Modular" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Connectors" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MTBF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cables" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PSU_Pc" Member="Pcs" ThisKey="ID" OtherKey="PSU_ID" Type="Pc" />
      <Association Name="PSU_Pc1" Member="Pc1s" ThisKey="ID" OtherKey="PSU_ID" Type="Pc1" />
      <Association Name="PartsStock_PSU" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_PSU" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RAM" Member="RAMs">
    <Type Name="RAM">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Speed" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Latency" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Voltage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Channel_Config" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="RAM_MoboToRam" Member="MoboToRams" ThisKey="ID" OtherKey="RAM_ID" Type="MoboToRam" />
      <Association Name="RAM_Pc" Member="Pcs" ThisKey="ID" OtherKey="RAM_ID" Type="Pc" />
      <Association Name="RAM_MoboToRam1" Member="MoboToRam1s" ThisKey="ID" OtherKey="RAM_ID" Type="MoboToRam1" />
      <Association Name="RAM_Pc1" Member="Pc1s" ThisKey="ID" OtherKey="RAM_ID" Type="Pc1" />
      <Association Name="PartsStock_RAM" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_RAM" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Speaker" Member="Speakers">
    <Type Name="Speaker">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Satellite_Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Satellite_Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubWoofer_Dimensions" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubWoofer_Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="controls" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[System Requirements]" Member="System_Requirements" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Features" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Speaker_Pc" Member="Pcs" ThisKey="ID" OtherKey="Speaker_ID" Type="Pc" />
      <Association Name="Speaker_Pc1" Member="Pc1s" ThisKey="ID" OtherKey="Speaker_ID" Type="Pc1" />
      <Association Name="PartsStock_Speaker" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_Speaker" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AirCooler" Member="AirCoolers">
    <Type Name="AirCooler">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Fan_Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Compatibility" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Fan_RPM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Air_Flow" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Noise_Level" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Power_Connector" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Materials" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Features" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="AirCooler_CpuToAirCooler" Member="CpuToAirCoolers" ThisKey="ID" OtherKey="AC_ID" Type="CpuToAirCooler" />
      <Association Name="PartsStock_AirCooler" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PartCart" Member="PartCarts">
    <Type Name="PartCart">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Part_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Qua" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PartsStock_PartCart" Member="PartsStock" ThisKey="Part_ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="Client_PartCart" Member="Client" ThisKey="User_ID" OtherKey="User_ID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GPU" Member="GPUs">
    <Type Name="GPU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Manufacturer" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Base_Clock_Speed" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Boost_Clock_Speed" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Stream_Processors" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Clock" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ports" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Digital_Resolution" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VR_Ready" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Recommended_Power_Supply" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Form_Factor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Slot_Width" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="GPU_GpuToMonitor" Member="GpuToMonitors" ThisKey="ID" OtherKey="GPU_ID" Type="GpuToMonitor" />
      <Association Name="GPU_Pc" Member="Pcs" ThisKey="ID" OtherKey="GPU_ID" Type="Pc" />
      <Association Name="PartsStock_GPU" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HDD" Member="HDDs">
    <Type Name="HDD">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Interface" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Sustained_Transfer_Rate" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rotational_Speed" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Load_Unload_Cycles" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Workload_Rate_Limit" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Power_Usage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Operating_Temp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="HDD_Pc" Member="Pcs" ThisKey="ID" OtherKey="HDD_ID" Type="Pc" />
      <Association Name="PartsStock_HDD" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SSD" Member="SSDs">
    <Type Name="SSD">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Cable_Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Connector" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Frequency_Response" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sound_Pressure_Level" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Microphone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MP_Frequency_Response" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MP_Pickup_Pattern" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MP_Sensitivity" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Colour" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Features" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Headset1_Pc" Member="Pcs" ThisKey="ID" OtherKey="Headset_ID" Type="Pc" />
      <Association Name="Headset1_Pc1" Member="Pc1s" ThisKey="ID" OtherKey="Headset_ID" Type="Pc1" />
      <Association Name="PartsStock_Headset1" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
      <Association Name="PartsStock1_Headset1" Member="PartsStock1" ThisKey="ID" OtherKey="ID" Type="PartsStock1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pc" Member="Pcs">
    <Type Name="Pc">
      <Column Name="PC_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PC_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Case_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mobo_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CPU_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RAM_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GPU_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cooler_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SSD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fan_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HDD_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PSU_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OS_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Num_Fans" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Num_SSD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Num_HDD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Monitor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Headset_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Keyboard_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mouse_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Speaker_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PCCase_Pc" Member="PCCase" ThisKey="Case_ID" OtherKey="ID" Type="PCCase" IsForeignKey="true" />
      <Association Name="LiquidCooler_Pc" Member="LiquidCooler" ThisKey="Cooler_ID" OtherKey="ID" Type="LiquidCooler" IsForeignKey="true" />
      <Association Name="GPU_Pc" Member="GPU" ThisKey="GPU_ID" OtherKey="ID" Type="GPU" IsForeignKey="true" />
      <Association Name="HDD_Pc" Member="HDD" ThisKey="HDD_ID" OtherKey="ID" Type="HDD" IsForeignKey="true" />
      <Association Name="Headset_Pc" Member="Headset" ThisKey="Headset_ID" OtherKey="ID" Type="Headset" IsForeignKey="true" />
      <Association Name="Keyboard_Pc" Member="Keyboard" ThisKey="Keyboard_ID" OtherKey="ID" Type="Keyboard" IsForeignKey="true" />
      <Association Name="Motherboard_Pc" Member="Motherboard" ThisKey="Mobo_ID" OtherKey="ID" Type="Motherboard" IsForeignKey="true" />
      <Association Name="Monitor_Pc" Member="Monitor" ThisKey="Monitor_ID" OtherKey="ID" Type="Monitor" IsForeignKey="true" />
      <Association Name="Mouse_Pc" Member="Mouse" ThisKey="Mouse_ID" OtherKey="ID" Type="Mouse" IsForeignKey="true" />
      <Association Name="PSU_Pc" Member="PSU" ThisKey="PSU_ID" OtherKey="ID" Type="PSU" IsForeignKey="true" />
      <Association Name="RAM_Pc" Member="RAM" ThisKey="RAM_ID" OtherKey="ID" Type="RAM" IsForeignKey="true" />
      <Association Name="Speaker_Pc" Member="Speaker" ThisKey="Speaker_ID" OtherKey="ID" Type="Speaker" IsForeignKey="true" />
      <Association Name="SSD_Pc" Member="SSD" ThisKey="SSD_ID" OtherKey="ID" Type="SSD" IsForeignKey="true" />
      <Association Name="CPU_Pc" Member="CPU" ThisKey="CPU_ID" OtherKey="ID" Type="CPU" IsForeignKey="true" />
      <Association Name="Fan_Pc" Member="Fan" ThisKey="Fan_ID" OtherKey="ID" Type="Fan" IsForeignKey="true" />
      <Association Name="PcStock_Pc" Member="PcStock" ThisKey="PC_ID" OtherKey="ID" Type="PcStock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MoboToCase" Member="MoboToCases">
    <Type Name="MoboToCase">
      <Column Name="Mobo_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Case_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="PCCase_MoboToCase" Member="PCCase" ThisKey="Case_ID" OtherKey="ID" Type="PCCase" IsForeignKey="true" />
      <Association Name="Motherboard_MoboToCase" Member="Motherboard" ThisKey="Mobo_ID" OtherKey="ID" Type="Motherboard" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MoboToCpu" Member="MoboToCpus">
    <Type Name="MoboToCpu">
      <Column Name="Mobo_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CPU_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Motherboard_MoboToCpu" Member="Motherboard" ThisKey="Mobo_ID" OtherKey="ID" Type="Motherboard" IsForeignKey="true" />
      <Association Name="CPU_MoboToCpu" Member="CPU" ThisKey="CPU_ID" OtherKey="ID" Type="CPU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CPU" Member="CPUs">
    <Type Name="CPU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Cores" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Threads" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Base_Clock" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Boost_Clock" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Total_Cache" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Chipset" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TDP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Temp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="System_Memory_Speed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="System_Memory_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Memory_Channels" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="CPU_CpuToAirCooler" Member="CpuToAirCoolers" ThisKey="ID" OtherKey="CPU_ID" Type="CpuToAirCooler" />
      <Association Name="CPU_CpuToLiquidCooler" Member="CpuToLiquidCoolers" ThisKey="ID" OtherKey="CPU_ID" Type="CpuToLiquidCooler" />
      <Association Name="CPU_Pc" Member="Pcs" ThisKey="ID" OtherKey="CPU_ID" Type="Pc" />
      <Association Name="CPU_MoboToCpu" Member="MoboToCpus" ThisKey="ID" OtherKey="CPU_ID" Type="MoboToCpu" />
      <Association Name="PartsStock_CPU" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fans" Member="Fans">
    <Type Name="Fan">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Series" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RPM" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Max_Air_Flow" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Noise" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Static_Pressure" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Input_Voltage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MTBF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cable_Length" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Num_Fans" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Warranty" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Fan_Pc" Member="Pcs" ThisKey="ID" OtherKey="Fan_ID" Type="Pc" />
      <Association Name="PartsStock_Fan" Member="PartsStock" ThisKey="ID" OtherKey="ID" Type="PartsStock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PcStock" Member="PcStocks">
    <Type Name="PcStock">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PC_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PcStock_PcSold" Member="PcSold" ThisKey="ID" OtherKey="PC_ID" Type="PcSold" Cardinality="One" />
      <Association Name="PcStock_Pc" Member="Pc" ThisKey="ID" OtherKey="PC_ID" Type="Pc" Cardinality="One" />
      <Association Name="PcStock_PcCart" Member="PcCarts" ThisKey="ID" OtherKey="Pc_ID" Type="PcCart" />
    </Type>
  </Table>
  <Table Name="dbo.PcCart" Member="PcCarts">
    <Type Name="PcCart">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pc_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Qua" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PcStock_PcCart" Member="PcStock" ThisKey="Pc_ID" OtherKey="ID" Type="PcStock" IsForeignKey="true" />
      <Association Name="Client_PcCart" Member="Client" ThisKey="User_ID" OtherKey="User_ID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
</Database>